### ISSUE TITLE
IPI not closing itself anymore after crash!

### ISSUE THREAD

**Issue by Gabeiq** [0x199/ps4-ipi#10]
Greetings.

I've been using IPI exclusively to install pkgs for almost one year, but today it crashed during an small dlc install,  after installing like 10-12 pkg small files before, and believe it or not, during the crash my ps4 was restarted and the pkg at the data folder was deleted.

Now IPI doesn't close itself anymore after adding the pkg at the download section, the notification pops up and then it stays on the blue screen, so I have to force close it manually.... Also, when I do this, the remaining time isn't show at the notification section. 

Tried to wait but it never closes, even after the installation...

Tried to delete / reinstall IPI but the problem remains the same with new installs.

Just to clarify, before the use, I'm renaming the pkgs  using small names, btw.

Is there a way for me to generate a log of the error?

I'm at 9.00  - Goldhen 2.3

Regards,

**Comment by Masamune3210** [comment]
There isnt much point to using IPI now that GoldHEN has native support for reading pkgs from /data/pkg, so honestly I would just switch to that

**Comment by AnimMouse** [comment]
It seems like the notification.db is full, delete all your notifications and download notifications and try to install using IPI again.
