### ISSUE TITLE
Stalled on blue screen when attempting to install large pkgs

### ISSUE THREAD

**Issue by viktory36** [0x199/ps4-ipi#2]
On goldHen 2.0b and fw 9.00,

The app works in installing smaller pkgs (tested two pkgs sub-100mb) but fails to installer larger pkgs, stalling out on a blue screen, no response or change (waited 15mins, large pkg size 30-40gb)

If small pkgs and large pkgs are attempted to be installed together, the small pkgs will install successfully and ps4-ipi will stall on a blue screen with failing to install the large pkg

The app works as expected when attempting to install only small pkgs

**Comment by toloxl** [comment]
rename your pkg files to be shorter
