### ISSUE TITLE
If the pkg name is too long, ipi will not detect it

### ISSUE THREAD

**Issue by carcaschoi** [0x199/ps4-ipi#3]
The original name of pkg file is
HP0082-CUSA19072_00-0000000000000000-A0100-V0103.pkg

After I rename it as 
1.pkg
It starts working

**Comment by Sch-LikA** [comment]
I confirm, I had two packages with long names, IPI just hang on blue loading screen. Renaming the packages to short names I could then open IPI ok and get the packages installed.

**Comment by gudge25** [comment]
i confirm too

**Comment by Dizzy611** [comment]
Same issue here, renaming EP1464-CUSA24653_00-0000000000000000-A0100-V0100.pkg to A.pkg allowed it to install, otherwise it hung on a blue screen.

**Comment by schlord** [comment]
>Yes, can confirm too. too long filenamewill not install. after renaming it started. thanks for your effort and happy holidays

**Comment by Buzbee** [comment]
It appears it only supports a string of 50 characters - and default ps4 names are 52 characters long : 48+.+pkg
so you need to delete 2 of the 48 characters up front on all the pkg names.

**Comment by Ekibunnel** [comment]
quite annoying

**Comment by Jektt** [comment]
It's not just the filenames. There is also something else preventing detection of pkgs, if you have 10, 20, etc. pkg files, 1.pkg, 2.pkg, etc. IPI will not find and install them all. GoldHEN package installer does.

**Comment by iMonZ** [comment]
Same issue

**Comment by TomFeliway** [comment]
Think I found the issue, file path (including name) is limited to 255 chars. Likely running over the 255 causes the installer to freeze. If I find some time, ill submit a pull request.

https://github.com/0x199/ps4-ipi/issues/5#issue-1097043641

**Comment by 0x199** [comment]
Fixed with the latest release now available.

**Comment by CrashoverrideCS** [comment]
This is still impacting me. Also it says that the file failed to install.
