### ISSUE TITLE
Filepath limited to 255

### ISSUE THREAD

**Issue by TomFeliway** [0x199/ps4-ipi#5]
https://github.com/0x199/ps4-ipi/blob/50afcb2189f25dd193e8f8c9b18523a9a571ffad/Internal%20PKG%20Installer/installer.cpp#L82
https://github.com/0x199/ps4-ipi/blob/50afcb2189f25dd193e8f8c9b18523a9a571ffad/Internal%20PKG%20Installer/installer.cpp#L83

Line 82 and 83 causes an issue with large package names.

Did you want me to issue a PR for it?

**Comment by 0x199** [comment]
Thanks, there's already a pending PR with a fix. Will test that soon.

**Comment by TomFeliway** [comment]
Awesome, great work and thanks :)

**Comment by 0x199** [comment]
Fixed with the latest release now available.
